### PR TITLE
Add ability to tail application logs during start

### PR DESCRIPTION
**Pull request by aeijdenberg**
Fixes <https://github.com/contraband/autopilot/issues/38>.

Also fixes some panics that would occur when invoked with no arguments.

The change itself isn't very big, and is in the first commit and follows the technique suggested in <https://github.com/cloudfoundry/cli/issues/1031#issuecomment-267966014>.

The second commit took the longest - and is my attempt to update `Godep` - I think this builds cleanly now.

### CODE REVIEW

**Comment by aeijdenberg** [comment]
I forgot to actually document how to invoke, simply add `--show-app-log`

**Comment by aeijdenberg** [comment]
@xoebus - this repo seems a little quiet...

 Are you still accepting PRs for review, or do you have other suggestions?

**Comment by xoebus** [comment]
You're right: there's hasn't been much progress here lately. Due to the
(hopefully) imminent start of the Cloud Controller work  which will
allow these features natively I'm probably only going to merge fixes
rather than new features from now on but I'll try and get through the
existing pull requests.
On Sun, Nov 5, 2017, at 19:18, Adam Eijdenberg wrote:
> @xoebus[1] - this repo seems a little quiet...


> Are you still accepting PRs for review, or do you have other
> suggestions?> — You are receiving this because you were mentioned. Reply to this
> email directly, view it on GitHub[2], or mute the thread[3].> 


Links:

  1. https://github.com/xoebus
  2. https://github.com/contraband/autopilot/pull/43#issuecomment-342036371

**Comment by xoebus** [comment]
@aeijdenberg Thank you so much for you patience. I've cherry picked this commit onto my master and resolved some conflicts but there were import issues in the dependencies that I've had to revert. The problem is in the CLI import code but they've already fixed the problem on master. I'll wait for the next CLI release and try again.

**Comment by xoebus** [comment]
The CLI team has said that they'll be releasing today or tomorrow so I should be able to look at this soon.

**Comment by aeijdenberg** [comment]
Abandoning this PR in favor of https://github.com/contraband/autopilot/pull/44, where I think I've addressed the `dep` issues.

**Comment by dan-kirberger** [comment]
@xoebus - Could you share any info on this Cloud Controller work?

**Comment by xoebus** [comment]
@dan-kirberger https://docs.google.com/document/d/116I_mOWjZcPeIbUvvsh-jAcwpoE_mGPD_SkCel5xXuU/edit

**Pull request closed without merging**
