### PR TITLE
correct plugin version number

### PR DESCRIPTION
**Pull request by afeld**

### CODE REVIEW

**Comment by loksonarius** [comment]
Was literally about to submit this change myself.
Please merge 🙏

**Comment by xoebus** [comment]
Thanks for the PR. I'll try and merge this in and get a new published release out soon.

**Comment by camelpunch** [comment]
Would also like to see the version number corrected ;)

**Comment by xoebus** [comment]
Cut a new version with correct version number (0.0.4) and submitted to plugin repo: https://github.com/cloudfoundry/cli-plugin-repo/pull/193.

Thanks for your patience!

**Pull request merged**
