### PR TITLE
Handle failed CI cases better on subsequent runs

### PR DESCRIPTION
**Pull request by aeijdenberg**
Fixes some of the problems identified in <https://github.com/contraband/autopilot/issues/37>.

This builds on top of <https://github.com/contraband/autopilot/pull/43>.

We now have one actions code path that handles:

1. No apps running.
2. App running, no venerable.
3. App not running, venerable app running.
4. Both app and venerable app running.

Previously only (1) and (2) were handled correctly.

### CODE REVIEW

**Comment by aeijdenberg** [comment]
(gentle ping)

We've been using this patch in prod now for a number of projects for a number of weeks, including health checkers that deploy a new release every 5 minutes, and we haven't seen issues.

I'll be happy to rebase to fix the minor merge conflict, but only if it's likely to get a review. :)

**Comment by drnic** [comment]
@vito @contraband possible to merge; and then push into cf-resource?

**Comment by aeijdenberg** [comment]
I've just rebased this on `master`, which now uses `dep`.

I spent a few hours banging my head against the wall, as `dep ensure` wouldn't report clean, even on `master`.

I eventually removed `Gopkg.toml`, `Gopkg.lock` and `vendor/` dirs, and then ran `dep init` in a clean environment.

This seemed to create a cleaner set of `Gopkg` files, from which I used as a base to cherry-pick and merge both of the changes that we've been using the past few months:

- Ability to tail logs
- Fixes so that this won't fail if a previous deploy failed.

Hope this makes it easier to merge.

**Comment by aeijdenberg** [comment]
Wow, this actually removes nearly 1 MILLION lines of code... (presumably because `dep init` now excludes vendored test packages by default)

**Comment by xoebus** [comment]
Thank you! I'll review this tomorrow PST.

**Comment by xoebus** [comment]
Thank you!

Merged, released, and included in the `cf-resource` in https://github.com/concourse/concourse/commit/40769f4632317ed9cb25709608b4a5c02508aaca.

**Comment by drnic** [comment]
Awesome.

________________________________

**Comment by aeijdenberg** [comment]
Thanks @xoebus - though note that I think you'll also need to merge https://github.com/concourse/cf-resource/pull/40 in order to be able to pass the `--show-app-log` parameter through `cf-resource`.

**Comment by xoebus** [comment]
Thanks for the heads up! I'll let @vito know.

**Pull request merged**
